### ISSUE TITLE
Missing minor informations

### ISSUE THREAD

**Issue by stefanak-michal** [neo4j-drivers/neo4j-drivers.github.io#33]
Hi.

Message BEGIN for version 3 by documention doesn't have IGNORED as response in list of "Valid Summary Messages:" but later there is server response IGNORED. Question is if version <=3 have this type of server response it should be added.

Also RESET message doesn't have described response in V3 and higher. But it seems there is same like it's described in V1.

https://7687.org/bolt/bolt-protocol-message-specification-3.html#request-message---begin

**Comment by robsdedude** [comment]
Thanks for raising this. Iirc, you already mentioned this (along with other comments) in Slack. We already added it to our Trello wall, but so far none of us found the time to look into this. I'll leave this issue open for better visibility. [internal link to the Trello card](https://trello.com/c/9LNQ7MSJ)

**Comment by stefanak-michal** [comment]
Yes I had a feeling like Slack didn't have proper attention. I wanted to put it on proper related place. I'm sorry for duplicity.

**Comment by robsdedude** [comment]
This issue should be addressed by https://github.com/neo4j/docs-bolt/pull/34

If not, please open a new issue in the linked repository.
