### ISSUE TITLE
5.0

### ISSUE THREAD

**Issue by lyndonbauto** [neo4j-drivers/neo4j-drivers.github.io#35]
Hi, is there any information on Bolt 5.0? I am wondering when the protocol documentation will be updated. I noticed the Java driver is currently being worked on so I figure there must be a list of new features added, I was hoping to get a high level understanding of what is added or if possible the protocol details.

Thank you!

**Comment by robsdedude** [comment]
I will close this issue as the new bolt documentation can be found here: https://github.com/neo4j/docs-bolt

Bolt 5.0-5.2 have been published there already, and 5.3 is on the way. Generally speaking, the protocol documentation is written after the respective server/driver versions are published as we want to keep us the option of changing the new protocol versions right until the day of release.
