### ISSUE TITLE
Jolt

### ISSUE THREAD

**Issue by lyndonbauto** [neo4j-drivers/neo4j-drivers.github.io#36]
I just came across the draft for Jolt in the code base here. I was wondering if there's any more information on this? I can see it is being used by some drivers so I suspect it is out of draft form.

Is this something that is being actively used? Is there future versions coming out? Any information on the direction of this project would be appreciated, thank you!

**Comment by johannessen** [comment]
See <https://neo4j.com/docs/http-api/4.4/actions/result-format/#_jolt>.

Unfortunately, Jolt is currently literally a one-way street, only being available for receiving results _from_ the server. For sending queries _to_ the server, you’ll need to use plain old JSON, which means you can’t use spatial or temporal values as parameters. I’m hoping this’ll be addressed in Neo4j 5.

**Comment by lyndonbauto** [comment]
@johannessen Thanks for the quick response, I am looking forward to learning more about Neo4J 5!
