### ISSUE TITLE
Inconsistent PackStream terminology

### ISSUE THREAD

**Issue by 0xSiO** [neo4j-drivers/neo4j-drivers.github.io#5]
The term 'tag byte' to refer to the type of a PackStream structure is inconsistent with the terminology given on the [v1 protocol documentation](https://boltprotocol.org/v1/#structures), where the term 'signature' is used, as well as in the official Java driver source.

Additionally, the term 'Dictionary' to refer to a mapping of strings to values is inconsistent with the term 'Map' in the [v1 protocol docs](https://boltprotocol.org/v1/#maps), the [Cypher manual](https://neo4j.com/docs/cypher-manual/current/syntax/values/#composite-types), the [driver manual](https://neo4j.com/docs/driver-manual/4.1/cypher-workflow/#driver-type-mapping), and the official Java driver source.

**Comment by fbiville** [comment]
Hi @lucis-fluxum, thanks for reporting the issue and apologies for the late response.

boltprotocol.org is not an official resource and is not maintained by Neo4j folks, so it is unlikely that inconsistencies between the two documentations will be fixed (and more may appear in the future).

I'll let @technige decide whether we want to rename `Dictionary` to `Map` in the specs.
It is worth noting that both the Java Driver and Cypher are JVM artefacts which may explain why they picked `Map`, which is a standard Java type.

**Comment by robsdedude** [comment]
@fbiville Can this one be closed, as boltprotocol.org is not maintained by us?
